---
- name: Update apt repositories, then upgrade
  hosts: MYHOSTS # replace with actual host file name

  tasks:
   - name: Update and upgrade
     become: true
     ansible.builtin.apt:
      update_cache: true
      upgrade: true
